### PR TITLE
Fix #466 - Not CATCH bug?

### LINKED ISSUE #466: Not CATCH bug?
### **Before/읽어주세요**

Make sure that you have used `/trg debug` so that the more detailed error message will show up in the console.
신고전에 `/trg debug` 명령어를 사용해서 디버그 모드를 켜주세요. 그래야 콘솔창에 더 자세한 정보가 나옵니다.

---

**Describe the bug/버그 증상**
17번 라인에서 해당 파일이 없으면 java.lang.reflect.InvocationTargetException/java.io.FileNotFoundException 로 Catch 되어야 하는데 catch로 넘어가지 않은 상황입니다.

If the file does not exist on line 17, it should be caught as java.lang.reflect.InvocationTargetException/java.io.FileNotFoundException, but it is not passed to catch.

**Server information/서버 정보**
1. Paper 1.16.5, Java 11 OpenJDK
2. 3.3.0.6 - Beta

**Error message/에러 메시지**
If error message (in red color) shows up in Minecraft client or on the console, report it here
에러메시지 (빨간색) 가 나타났다면 클라이언트와 콘솔의 메시지를 올려주세요.
image

**Others/그 밖의 정보들**

[11:36:16 INFO]: Limu_lhw issued server command: /filetest //커멘드 실행 (Command Execute)
[11:36:16 WARN]: java.lang.reflect.InvocationTargetException //라인 17 Exception (Line 17 Exception)
[11:36:16 INFO]: 2 //라인 19
[11:36:16 INFO]: :/ //라인 28. finally 씬

### PR DESCRIPTION
**Pull request by Ioloolo**
We can't catch invoked-method-error in the TRY-CATCH statements.
because ReflectionUtil handle the error internally, not Caller.

### CODE REVIEW

**Comment by wysohn** [comment]
Thank you so much! Will look into it soon

File: core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java [hunk 1]
```diff
@@ -770,6 +770,42 @@ public void testTryCatchFinally2() throws Exception {
...
+        Lexer lexer = new Lexer(text, charset);
+        Parser parser = new Parser(lexer);
+
+        Node root = parser.parse();
+
+        Map<String, Executor> executorMap = new HashMap<>();
+        executorMap.put("VERIFY", (timing, vars, context, args) -> {
+            Assert.assertEquals(true, args[0]);
+            return null;
+        });
```
Comment (wysohn) [inline core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java:800]: Looking all good!

Can we use mock&verify pattern instead though?

Don't forget to return 'null' with when() or the default return value will be 0, so the interpreter will stop right away (cause EXIT is integer 0)

ex)
https://github.com/TriggerReactor/TriggerReactor/blob/b2c9ea077f9984f688066b0ca6e6a830d5ed2d56/core/src/test/java/io/github/wysohn/triggerreactor/core/script/interpreter/TestInterpreter.java#L555

**Review by wysohn — CHANGES_REQUESTED** [review]

**Review by wysohn — APPROVED** [review]
Thank you!
